### ISSUE TITLE
Groovy 5 mode is not usable

### ISSUE THREAD

**Issue by Vampire** [groovy-console/groovy-web-console#381]
The Groovy 5 mode uses Spock 2.3-groovy-4.0.
This is not compatible as Spock checks the compatibility.
You could set the `spock.iKnowWhatImDoing.disableGroovyVersionCheck` system property though to ignore the version check and hope it works, or remove Spock until a 5.0 variant exists.
Currently even if you execute an empty script, you get the version error from Spock.

**Comment by leonard84** [comment]
You don't get an error. You only get the output from spock, because that property is set.

> Executing Spock 2.3.0-groovy-4.0 with NOT compatible Groovy version 5.0.0-alpha-8 due to set spock.iKnowWhatImDoing.disableGroovyVersionCheck system property. This is unsupported and may result in weird runtime errors!

**Comment by Vampire** [comment]
Ah, sorry, misinterpreted.
But probably confusing for people just wanting to do something with Groovy.
